# docker compose file to run ebox-elexis with elexis-server
version: '2'
services:
  elexisserver:
    image: "medevit/elexis-server:1.3"
    ports:
      - "7234:7234"
      - "8380:8380"
  eboxelexis:
    image: "medevit/ebox-elexis"
    command: -Dapplication.elexis.server.baseUrl="http://elexisserver"
    links:
      - elexisserver:elexisserver
    ports:
      - "9000:9000"
    stdin_open: true